version: "3"

services:   
   hotelapp:      
      build: 
         context: .
         dockerfile: Dockerfile
      depends_on:
         - mysql8
      image: "hotelapp:1.0"
      container_name: hotel      
      ports:
         - "8909:22"
      volumes:
         - .:/home/app
   mysql8:
      image: "mysql:8.0.29"
      container_name: mysql8      
      environment:
         - MYSQL_ROOT_PASSWORD=password
      volumes:
         - "hotelmysql:/var/lib/mysql"
volumes:
   hotelmysql:
